### ISSUE TITLE
Complete Readme

### ISSUE THREAD

**Issue by rallinator7** [rallinator7/elixir-chatter#1]
## User Story
As a user of this repository, I would like to be able to have directions so that I can successfully use this demo as a learning tool

## Description
The Readme is pretty incomplete right now.  Everything correctly works in the mage file, but we need to make sure that users know what order they need to execute the commands as well as why they are running each step.  These are the main parts we need to focus on:
- Creating the Docker Images
- Deploying Images with Docker/Docker-Compose
- Installing a Kind Cluster
- Deploying into Kind

The images for each of these sections have been completed and are already in the Readme, so we'd just need to highlight the mage steps.

## Tasks

Complete Documentation for:
-  [ ] Creating the Docker Images
-  [ ] Deploying Images with Docker/Docker-Compose
-  [ ] Installing a Kind Cluster
-  [ ] Deploying into Kind
