### ISSUE TITLE
Add Continuous Integration and Continuous Deployment

### ISSUE THREAD

**Issue by rallinator7** [rallinator7/elixir-chatter#3]
## User Story
As a user, I would like to see how to use continuous deployment so that I am not deploying my helm charts by hand

## Description
We are currently deploying all of our operators and deployments by hand through the mage file.  This works for the demonstration, but it does not show how to update the app when we make changes to it.  It'd be cool to add a second kind cluster, a development cluster, that could hold the github runner operator and argocd operator and relabel the current cluster as "production" to simulate the full cycle of ci and cd.

If this were to be added, I could see this repository being something someone could fork and just start adding pieces to the phoenix app.  It could be a cookie cutter ci/cd for phoenix applications in kubernetes.

## Tasks
- [ ] Add github runner operator
- [ ] Add argocd operator
- [ ] Add second Kind cluster
- [ ] UpdateReadme
