### ISSUE TITLE
Convert to Mix Tasks

### ISSUE THREAD

**Issue by rallinator7** [rallinator7/elixir-chatter#4]
## User Story
As a user of this rep, I would like to be able to accomplish everything I need to run in this project with elixir so that I only need to use a single language to get up and running.

## Description
We are currently using golang and mage to run our continuous integration.  Although I do believe this is the best way to do this, Others may not want to have to install another language/dependency.  I'd like to use mix tasks so that it can be OS agnostic.  All this pieces needed to run tests and docker builds should be converted to elixir.

## Tasks
- [x] Convert CI to elixir
- [x] Convert Docker pieces to mix tasks
- [x] Convert Kubernetes pieces to mix tasks
